#ifndef MOUSE_BUTTON_CODES_HDR
#define MOUSE_BUTTON_CODES_HDR

//From GLFW3.h
#define GUST_MOUSE_BUTTON_1         0
#define GUST_MOUSE_BUTTON_2         1
#define GUST_MOUSE_BUTTON_3         2
#define GUST_MOUSE_BUTTON_4         3
#define GUST_MOUSE_BUTTON_5         4
#define GUST_MOUSE_BUTTON_6         5
#define GUST_MOUSE_BUTTON_7         6
#define GUST_MOUSE_BUTTON_8         7
#define GUST_MOUSE_BUTTON_LAST      GUST_MOUSE_BUTTON_8
#define GUST_MOUSE_BUTTON_LEFT      GUST_MOUSE_BUTTON_1
#define GUST_MOUSE_BUTTON_RIGHT     GUST_MOUSE_BUTTON_2
#define GUST_MOUSE_BUTTON_MIDDLE    GUST_MOUSE_BUTTON_3

#endif // !MOUSE_BUTTON_CODES_HDR
